version: '3.7'

services:
  app:
    image: ambientum/php:7.3-nginx
    container_name: backend-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis

  scheduler:
    image: ambientum/php:7.3
    container_name: backend-scheduler
    volumes:
      - .:/var/www/app
    command: /bin/bash scripts/scheduler.sh

  worker:
    image: ambientum/php:7.3
    container_name: backend-worker
    volumes:
      - .:/var/www/app
    command: php artisan queue:listen

  mysql:
      image: mysql:5.7
      container_name: backend-database
      volumes:
        - backenddata:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=backend

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  backenddata:
